MyStore/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyStore.domainDB.Abstract;
using MyStore.domainDB.Entities;

namespace MyStore.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        //repository declaration
        private IProductRepository _repository;

        //contructor for dependency resolver
        public AdminController(IProductRepository repo)
        {
            _repository = repo;

        }
       
        //GET all product list
        public ViewResult Index()
        {
            return View(_repository.Products);
        }

        //EDIT the product from list
        public ViewResult Edit(int productId)
        {
            Product products = _repository.Products
                .FirstOrDefault(p => p.ProductId == productId);

            return View(products);

        }

        //UPDATE product and also use this for creating a new product
        [HttpPost]
        public ActionResult Edit(Product product, HttpPostedFileBase image = null)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    product.ImageMimeType = image.ContentType;
                    product.ImageData = new byte[image.ContentLength];
                    image.InputStream.Read(product.ImageData, 0, image.ContentLength);
                        

                }
                _repository.SaveProduct(product);
                TempData["message"] = string.Format("{0} has been updated", product.ProductName);
                return RedirectToAction("Index");
            }
            else
            {
                //there is something wrong with the data values 
                return View(product);
            }

        }

        //GET empty from for new product
        public ViewResult Create()
        {
                       
            return View("Edit", new Product());

        }

        //DELETE method
        public ActionResult Delete(int productId)
        {
            Product deleteProduct = _repository.DeleteProduct(productId);
            if (deleteProduct != null)
            {
                TempData["message"] = string.Format("{0} was deleted", deleteProduct.ProductName);
            }

            return RedirectToAction("Index");

        }
    }
}

MyStore/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyStore.domainDB.Abstract;
using MyStore.domainDB.Entities;
using MyStore.Models;
using MyStore.HtmlHelpers;
using Ninject.Infrastructure.Language;

namespace MyStore.Controllers
{
    public class ProductController : Controller
    {
        //repository declaration
        private IProductRepository _repository;
        public int PageSize = 6;

        //constructor for dependency resolver
        public ProductController(IProductRepository productRepository)
        {
            this._repository = productRepository;

        }
        //GET: Product
        //public ViewResult List()
        //{
        //    return View(_repository.Products);
        //}

        //GET products from db to list
        public ViewResult List(string category, int page = 1)
        {           

            ProductListViewModel model = new ProductListViewModel
            {
                
                Products = _repository.Products
                .Where(p => category == null || p.SubCategory.ToLower() == category.ToLower())
                .OrderBy(p => p.ProductId)
                .Skip((page - 1) * PageSize)
                .Take(PageSize),

                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    Totalitems = category == null ? _repository.Products.Count() : _repository.Products.Count(e => e.SubCategory.ToLower() == category.ToLower())
                },
                CurrentCategory = category
                               
            };


            return View(model);

            //  return View(_repository.Products.OrderBy(p => p.ProductId).Skip((page - 1) * PageSize).Take(PageSize));
        }

        ////GET products from db to list
        //public ViewResult Search(string searchString, int page = 1)
        //{
        //    ProductListViewModel model = new ProductListViewModel
        //    {

        //        Products = _repository.Products
        //        .Where(p => searchString == null || p.SubCategory.ToLower() == searchString)
        //        .OrderBy(p => p.ProductId)
        //        .Skip((page - 1) * PageSize)
        //        .Take(PageSize),

        //        PagingInfo = new PagingInfo
        //        {
        //            CurrentPage = page,
        //            ItemsPerPage = PageSize,
        //            Totalitems = searchString == null ? _repository.Products.Count() : _repository.Products.Count(e => e.SubCategory.ToLower() == searchString)
        //        },
        //        CurrentCategory = searchString
        //    };
        //    return View(model);
        //    //  return View(_repository.Products.OrderBy(p => p.ProductId).Skip((page - 1) * PageSize).Take(PageSize));

        //}

        //Get product details for detail view
        public ActionResult ProductDetail(int id)
        {
            // IEnumerable<Product> productD =_repository.Products.Where(p => p.ProductId == id);

            Product productD = _repository.Products.FirstOrDefault(p => p.ProductId == id);

            return View(productD);
        }

        //retrieve image from db
        public FileContentResult GetImage(int productId)
        {
            Product prod = _repository.Products.FirstOrDefault(p => p.ProductId == productId);
            if (prod != null)
            {
                return File(prod.ImageData, prod.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
       
    }
}

MyStore/Views/Admin/Edit.cshtml
@model MyStore.domainDB.Entities.Product

@{
    ViewBag.Title = "Edit - Product";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    HtmlHelper.ClientValidationEnabled = false;
    HtmlHelper.UnobtrusiveJavaScriptEnabled = false;

}

<h2 class="text-center panel panel-heading">Edit a Product detail</h2>


<div class="panel panel-body">
   <div class="col-sm-offset-1 col-sm-4">
       
    @using (Html.BeginForm("Edit", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {

        @Html.HiddenFor(m => m.ProductId)
        foreach (var property in ViewData.ModelMetadata.Properties)
        {
            //if (property.PropertyName != "ProductId")
            switch (property.PropertyName)
            {
                case "ProductId":
                case "ImageData":
                case "ImageMimeType":
                    break;

                default:

                    <div class="form-group">
                        <label>@(property.DisplayName ?? property.PropertyName)</label>
                        @if (property.PropertyName == "Description")
                        {
                            @Html.TextArea(property.PropertyName, null, new { @class = "form-control", rows = 5 })
                        }
                        else if (property.PropertyName == "Price")
                        {
                            @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })
                        }
                        else
                        {
                            @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })
                        }
                        @Html.ValidationMessage(property.PropertyName)
                    </div>

                    break;
            }
        }

        <div class="form-group">
            <div style="position:relative">
                <label>Upload Image</label>
                <a class="btn" href="javascript:">
                    Choose File...
                    <input type="file" name="Image" size="40"
                           style="position:absolute; z-index:2; top:0; left:0; filter:alpha(opacity=0); opacity:0; background-color:transparent;
                                            color:transparent;" onchange='$("#upload-file-info").html($(this).val());' />
                </a>
                <span class="label label-info" id="upload-file-info"></span>
            </div>
        </div>

             <div class="form-group">
                 <p>Image Uploaded</p>
                @if (Model.ImageData != null)
                {
                    <img class="img-thumbnail img-responsive" width="200" height="300" src="@Url.Action("GetImage", "Product", new { Model.ProductId })" />

                }
                else
                {
                    <div class="form-control-static">NO Uploaded Image</div>


                }
                
            </div>
            <div class="text-center">
                <input type="submit" value="Save" class="btn btn-success" />
                @Html.ActionLink("Cancel and Return to Product List", "Index", new { @class = "btn btn-default" })
            </div>
    }
    </div>
</div>
    @*<div class="row well">
    <p>Image URL</p>
    <img src="@Url.Content(Model.Image)" width="200" height="300" class="img-responsive img-thumbnail" alt="" />
</div>*@

MyStore/Views/Admin/Index.cshtml
@model IEnumerable<MyStore.domainDB.Entities.Product>

@{
    ViewBag.Title = "Admin: All_Products";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h3 class="text-center">KidsLearning Store Admin Panel </h3>
<div class="panel panel-default">
    <div class="panel-heading">
        <h3>All Products</h3>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-condensed table-bordered">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.ProductName)
                    </th>

                    <th>
                        @Html.DisplayNameFor(model => model.Price)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Category)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.SubCategory)
                    </th>
                    <th>
                        Actions
                    </th>

                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.ActionLink(item.ProductName, "Edit", new { item.ProductId })
                            @*@Html.DisplayFor(model => item.ProductName)*@
                        </td>
                        <td>
                           @item.Price.ToString("c")
                        </td>
                        <td>
                            @Html.DisplayFor(model => item.Category)
                        </td>
                        <td>
                            @Html.DisplayFor(model => item.SubCategory)
                        </td>

                        <td>
                            <!--Edit action-->
                            @using (Html.BeginForm())
                            {
                                <div class="col-md-3">
                                    @Html.ActionLink("Edit", "Edit", new { item.ProductId }, new { @class = "btn btn-default btn-xs" })

                                    @*@Html.Hidden("ProductId", item.ProductId)*@
                                    @*<input type="submit" class="btn btn-default btn-xs blo" value="Edit" />*@
                                </div>
                            }

            <!--Delete action-->
                            <div class="col-md-3">
                                @using (Html.BeginForm("Delete", "Admin"))
                                {
                                    @Html.Hidden("ProductId", item.ProductId)
                                    <input type="submit" class="btn btn-default btn-xs" value="Delete" />

                                }
                            </div>
                        </td>
                    </tr>
                                }
            </table>
    </div>
    <div class="panel-footer">
        <p>
            @Html.ActionLink("Add New product", "Create", null, new { @class = "btn btn-default" })
        </p>
    </div>
</div>