MyStore/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyStore.domainDB.Abstract;
using MyStore.domainDB.Entities;
using MyStore.Models;

namespace MyStore.Controllers
{
    public class CartController : Controller
    {
        //repository declaration
        private IProductRepository _repository;
        private IOrderProcessor orderProcessor;

        //constructor for dependency resolver
        public CartController(IProductRepository repo, IOrderProcessor proc)
        {
            _repository = repo;
            orderProcessor = proc;
        }

        //add to cart each item
        public RedirectToRouteResult AddToCart(Cart cart, int productId, string returnUrl)
        {
            Product product = _repository.Products.FirstOrDefault(p => p.ProductId == productId);

            if (product!=null)
            {
                cart.AddItem(product,1);
                //GetCart().AddItem(product, 1);
            }
            return RedirectToAction("Index", new {returnUrl});

        }

        //remove item from current cart
        public RedirectToRouteResult RemoveFromCart(Cart cart,int productId, string returnUrl)
        {
            Product product = _repository.Products.FirstOrDefault(p => p.ProductId == productId);

            if (product != null)
            {
                cart.RemoveLine(product);
                //GetCart().RemoveLine(product);
            }
            return RedirectToAction("Index", new {returnUrl});

        }

        //removed when modelbinder were implemented which will provide current cart object
        //private Cart GetCart()
        //{
        //    Cart cart = (Cart) Session["Cart"];
        //    if (cart == null)
        //    {
        //        cart = new Cart();
        //        Session["Cart"] = cart;
        //    }
        //    return cart;
        //    // throw new NotImplementedException();
        //}

        // GET: Cart
        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                //Cart = GetCart(), 
                ReturnUrl = returnUrl

            });
        }

        //cart summary
        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

        //display shipping detail page
        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }

        //submit order
        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (!cart.Lines.Any())
            {
                ModelState.AddModelError("", "Sorry, your cart is empty");
            }
            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }
            return View(new ShippingDetails());
        }
    }
}

MyStore/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyStore.domainDB.Abstract;

namespace MyStore.Controllers
{
    public class NavController : Controller
    {
        private IProductRepository _repository;

        public NavController(IProductRepository repo)
        {
            _repository = repo;
        }


        public PartialViewResult Menu(string category = null, bool horizontalLayout = false)
        {
            
            ViewBag.SelectedCategory = category;
            IEnumerable<string> subcategories = _repository.Products
                .Select(x => x.SubCategory)
                .Distinct()
                .OrderBy(x => x);

            string viewName = horizontalLayout ? "MenuHorizontal" : "Menu";

            return PartialView(viewName, subcategories);
        }

        public PartialViewResult SubMenu(string category = null)
        {
            ViewBag.SelectedCategory = category;
            
        IEnumerable<string> categories = _repository.Products
            .Select(x => x.Category)
            .Distinct()
            .OrderBy(x => x);

            return PartialView(categories);

        }



        // GET: Nav
        //public string Menu()
        //{
        //    return "Hello from NavController";
        //}
    }
}

MyStore/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyStore.domainDB.Abstract;
using MyStore.domainDB.Entities;
using MyStore.Models;
using MyStore.HtmlHelpers;
using Ninject.Infrastructure.Language;

namespace MyStore.Controllers
{
    public class ProductController : Controller
    {
        //repository declaration
        private IProductRepository _repository;
        public int PageSize = 6;

        //constructor for dependency resolver
        public ProductController(IProductRepository productRepository)
        {
            this._repository = productRepository;

        }
        //GET: Product
        //public ViewResult List()
        //{
        //    return View(_repository.Products);
        //}

        //GET products from db to list
        public ViewResult List(string category, int page = 1)
        {           

            ProductListViewModel model = new ProductListViewModel
            {
                
                Products = _repository.Products
                .Where(p => category == null || p.SubCategory.ToLower() == category.ToLower())
                .OrderBy(p => p.ProductId)
                .Skip((page - 1) * PageSize)
                .Take(PageSize),

                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    Totalitems = category == null ? _repository.Products.Count() : _repository.Products.Count(e => e.SubCategory.ToLower() == category.ToLower())
                },
                CurrentCategory = category
                               
            };


            return View(model);

            //  return View(_repository.Products.OrderBy(p => p.ProductId).Skip((page - 1) * PageSize).Take(PageSize));
        }

        ////GET products from db to list
        //public ViewResult Search(string searchString, int page = 1)
        //{
        //    ProductListViewModel model = new ProductListViewModel
        //    {

        //        Products = _repository.Products
        //        .Where(p => searchString == null || p.SubCategory.ToLower() == searchString)
        //        .OrderBy(p => p.ProductId)
        //        .Skip((page - 1) * PageSize)
        //        .Take(PageSize),

        //        PagingInfo = new PagingInfo
        //        {
        //            CurrentPage = page,
        //            ItemsPerPage = PageSize,
        //            Totalitems = searchString == null ? _repository.Products.Count() : _repository.Products.Count(e => e.SubCategory.ToLower() == searchString)
        //        },
        //        CurrentCategory = searchString
        //    };
        //    return View(model);
        //    //  return View(_repository.Products.OrderBy(p => p.ProductId).Skip((page - 1) * PageSize).Take(PageSize));

        //}

        //Get product details for detail view
        public ActionResult ProductDetail(int id)
        {
            // IEnumerable<Product> productD =_repository.Products.Where(p => p.ProductId == id);

            Product productD = _repository.Products.FirstOrDefault(p => p.ProductId == id);

            return View(productD);
        }

        //retrieve image from db
        public FileContentResult GetImage(int productId)
        {
            Product prod = _repository.Products.FirstOrDefault(p => p.ProductId == productId);
            if (prod != null)
            {
                return File(prod.ImageData, prod.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
       
    }
}

MyStore/Controllers/StartupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyStore.domainDB.Abstract;


namespace MyStore.Controllers
{
    public class StartupController : Controller
    {
        private IProductRepository _repository;
        public int PageSize = 6;

        public StartupController(IProductRepository productRepository)
        {
            this._repository = productRepository;

        }
        // GET: Startup
        public ActionResult Index()
        {
            IEnumerable<string> subcategories = _repository.Products
                .Select(x => x.SubCategory)
                .Distinct()
                .OrderBy(x => x);

            return View(subcategories);
        }

        public ViewResult Contact()
        {
            return View();
        }

    }


}

MyStore/Views/Shared/ProductSummary.cshtml
@model MyStore.domainDB.Entities.Product


<link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />
<link href="~/Content/themes/base/all.css" rel="stylesheet" />

<!--Display each product-->
<div class="panel panel-primary">
    <!--Productname and Price and click more for detail-->
    <div class="panel-heading">
        <table style="width:100%; height:70px;">
            <tr>
                <td><strong>@Model.ProductName</strong></td>
            </tr>
            <tr>
                <td>
                    <span class="pull-right label label-primary" style="font-size:1.0em;">@Model.Price.ToString("c")</span>
                </td>
            </tr>
        </table><a class="" href="@Url.Action("ProductDetail","Product", new {id=Model.ProductId})">more>></a>
    </div>
    <!--Image display-->
    <div class="panel-body text-center">
        <a class="" href="@Url.Action("ProductDetail","Product", new {id=Model.ProductId})">
            <img class="img-thumbnail img-responsive " width="200" height="250" src="@Url.Content(@Model.Image)" alt="" />
            @*@if (Model.ImageData != null)
                {
                                    <img class="img-thumbnail img-responsive" width="240" height="300" src="@Url.Action("GetImage", "Product", new {Model.ProductId })" />
                }
                else
                {
                    <img class="img-thumbnail img-responsive " width="240" height="300" src="@Url.Content(@Model.Image)" alt="" />
                }*@
        </a>
    </div>
    <!--Brief info about product-->
    <div class="panel-info">
        <div class="info_css">
            <label><b>Author: @Model.Author</b></label>
            <br />
            <label><b>Publisher: @Model.Publisher</b></label>
            @*<tr><td>Publisher: @Model.Publisher</td></tr>
                <tr><td>ISBN: @Model.ISBN</td></tr>*@
        </div>
        <!--add to cart icon-->
        <div>

            @using (Html.BeginForm("AddToCart", "Cart"))
            {
                <div class="pull-right">
                    @Html.HiddenFor(x => x.ProductId)
                    @Html.Hidden("returnUrl", Request.Url.PathAndQuery)

                    <input type="submit" class="btn btn-success pull-right addtocart-btn" style="padding:5px 10px;" value="Add to Cart" />
                </div>
            }
        </div>
    </div>
</div>
<script src="~/Scripts/jquery-1.10.2.js"></script>
<script src="~/Scripts/jquery-3.1.1.js"></script>
<script src="~/Scripts/jquery-ui-1.12.1.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

MyStore/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;

}
@using System.Web.Optimization;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    

    <link href="~/Content/bootstrap-flaty.css" rel="stylesheet" />
   
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />

    <!--Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <title>@ViewBag.Title</title>
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    
</head>
<body>
    <div class="navbar-header">
        <a href="@Url.Action("List","Product", new { @class = "btn btn-default btn-sm" })">Client Page</a>
    </div>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-succes">@TempData["message"]</div>
        }
        @RenderBody()
    </div>

</body>
</html>

MyStore/Views/Shared/_Layout.cshtml
@using System.Web.Optimization;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    
    <!--Customised bootstraptheme-->
    <link href="~/Content/bootstrap-flaty.css" rel="stylesheet" />
    <!--Font Awesom link for icons-->
    <script src="https://use.fontawesome.com/31424c71d6.js"></script>

    @*-------------------------||custome stylying||-------------------------*@

    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />

    <style>
        body {
            padding-top: 80px;
        }
    </style>
    <title>@ViewBag.Title</title>
</head>
<body>

    <!--top bar section for icons and login-->
    <div class="container navbar-fixed-top top_bar" style="background-color:#FDFDFD;">
        <div class="row">
            <div class="col-xs-4">
                <a href="" class="social_icon"><i class="fa fa-facebook-official icon_css"></i></a>
                <a href="" class="social_icon"><i class="fa fa-twitter icon_css"></i></a>
                <a href="" class="social_icon"><i class="fa fa-youtube-play icon_css"></i></a>
                <a href="" class="social_icon"><i class="fa fa-google-plus icon_css" style="font-size:1.1em; color:#18bc9c;"></i></a>
            </div>

            <div class="col-xs-8">
                <div class="pull-right visible-xs">
                    @Html.Action("Summary", "Cart")
                </div>
                <ul class="top_bar_control">
                    <li><a href="@Url.Action("Login","Account", "")">Login</a></li>
                    @*<li class="hidden-xs"><a href="@Url.Action("Login","Account", "")">Register</a></li>*@
                    @*<li><a href="@Url.Action("Login","Account", "")">Admin</a></li>*@
                </ul>

            </div>
        </div>
    </div>
    <!--logo and navigation -->
    <div class="navbar navbar-inverse navbar-fixed-top" style="margin-top:22px; margin-bottom:0;">
        <div class="container">
            <div class="row">
                <div class="col-xs-2">
                    <div class="navbar-header">
                        <a class="navbar-brand" href="@Url.Action("Index","Startup")">
                            <span class="hidden-xs">KidsLearning Store</span>
                            <div class="visible-xs">Kids</div>
                            <div class="visible-xs">Store</div>
                        </a>
                    </div>
                </div>
                <div class="col-xs-10" style="">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <!--cart summary for top_fixed nav-->
                    <div class="pull-right hidden-xs">@Html.Action("Summary", "Cart")</div>
                    <div class="collapse navbar-collapse" id="navbar-collapse">
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="@Url.Action("Index","Startup")">Home</a></li>
                            <li><a href="@Url.Action("Contact","Startup")">Contact</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div><!--Navigation ends-->
    <!--Banner section-->
    <div class="container-fluid banner_cs hidden-xs">
    </div><!--Ends banner-->
    <!--Category and content section-->
    <div class="container" style="margin-top:30px;">
        <div class="row panel content-cs">
            <!--category vertical standard-->
            <div id="category" class="col-sm-2 hidden-xs">
                @*<div id="category" class="col-sm-3 col-md-2 col-xs-3 hidden-xs">*@
                @Html.Action("Menu", "Nav")
            </div>
            <!--category horizontal for small devices-->
            <div class="col-xs-12 visible-xs navbar-fixed-top horizontan_menu">
                @Html.Action("Menu", "Nav", new { horizontalLayout = true })
            </div>
            <!--Content section-->
            <div class="col-sm-10 col-xs-12 body-content">
                @RenderBody()
            </div>
        </div>
        <hr />
        @*<footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>*@
    </div>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

</body>
</html>